# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-23 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('graph', models.ImageField(upload_to='graph_image')),
                ('image', models.ImageField(upload_to='mobile_image')),
            ],
        ),
        migrations.CreateModel(
            name='mobilesAmazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('review_no', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('delivery', models.IntegerField()),
                ('star1', models.IntegerField(default=0)),
                ('star2', models.IntegerField(default=0)),
                ('star3', models.IntegerField(default=0)),
                ('star4', models.IntegerField(default=0)),
                ('star5', models.IntegerField(default=0)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon', to='home.mobiles')),
            ],
        ),
        migrations.CreateModel(
            name='mobilesFlipkart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('review_no', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('delivery', models.IntegerField()),
                ('star1', models.IntegerField(default=0)),
                ('star2', models.IntegerField(default=0)),
                ('star3', models.IntegerField(default=0)),
                ('star4', models.IntegerField(default=0)),
                ('star5', models.IntegerField(default=0)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipkart', to='home.mobiles')),
            ],
        ),
        migrations.CreateModel(
            name='mobilesSnapdeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('review_no', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('delivery', models.IntegerField()),
                ('star1', models.IntegerField(default=0)),
                ('star2', models.IntegerField(default=0)),
                ('star3', models.IntegerField(default=0)),
                ('star4', models.IntegerField(default=0)),
                ('star5', models.IntegerField(default=0)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapdeal', to='home.mobiles')),
            ],
        ),
    ]
