# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-23 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_mobilessnapdeal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilesamazon',
            name='month_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mobilesamazon',
            name='week_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mobilesflipkart',
            name='month_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mobilesflipkart',
            name='week_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mobilessnapdeal',
            name='month_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mobilessnapdeal',
            name='week_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mobilesflipkart',
            name='delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mobilessnapdeal',
            name='delivery',
            field=models.IntegerField(default=0),
        ),
    ]
